[package]
name = "fpi"
version = "0.1.0"
authors = ["Matheus Cruz <mlcruz@inf.ufrgs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
druid = "0.7.0"